name: Check
on:
  push:
    paths:
      - "**.lua"
  pull_request:
    paths:
      - "**.lua"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck lint
        uses: lunarmodules/luacheck@v1
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
